name: escola_magica
description: "A new Flutter project."
ublish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  gallery_saver: ^2.0.3
  android_intent_plus: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tela_inicial.png
    - assets/tela_photos.png
